exports.STATUSCODES={
    INVALID_INPUT:400,
    NOT_FOUND:404,
    SUCEESS:200,
    NEW_REOCRD_INSERT:201,
    INTERNAL_SERVER_ERROR:500,
    DELETE_CODE:204
}

exports.STATUSMESSAGES={
    INVALID_lOGIN:"NO USER MATCH IN DATA ",
    INVALID_ID:"PLEASE SEND VALID USER ID",
    INVALID_SIGNUP:"PLEASE SEND ALL REQUIRED FIELD FOR USER CREATION",
    INTERNAL_SERVER:"INTERNAL SERVER ERROR OCCURE  PLEASE CHECK THE BELOW ERROR",
    NEW_RECORD_INSERT:"NEW RECORD HAS BEEN INSERTED",
    USER_ALREADY_CREATED:"USER IS ALREADY CREATED",
    GET_ALL_USERS :"GET ALL USERS",
    USER_UPDATE:"USER IS UPDATED ",
    USER_DATA_DELETED:"uSER DATA HAS BEEN DELETE",
    NOT_FOUND:"NOT_FOUND"
}

exports.emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
exports.TestEnv="Testing"